### ISSUE TITLE
Possibility of saving/loading states?

### ISSUE THREAD

**Issue by Herringway** [Mihail-K/markov#1]
It would be really handy to be able to dump and reload the internal state of a markov chain instead of repeatedly retraining it.

**Comment by mintyfresh** [comment]
I've already got a prototype of the feature in a local branch, will definitely work on getting it into master.

**Comment by Herringway** [comment]
excellent!

**Comment by mintyfresh** [comment]
As of the most recent version, `toJson` and `toMarkovChain(T)` functions have been added for encoding to and from JSON.

JSON is probably not the best for massive amounts of data, but it does provide a way to visualize the internal state of the chain. I'll work on adding a binary serialization option for a later version, as well.

**Comment by mintyfresh** [comment]
And then I decided I didn't like the existing serialization setup and decided to redo it, for the most part. Binary serialization is now also an option with your choice of `encodeJSON` and `encodeBinary` and corresponding decode functions.

**Comment by Herringway** [comment]
very nice. thank you
